### ISSUE TITLE
Impossibile to install pamac-flatpak by AUR

### ISSUE THREAD

**Issue by CavaleriOmar** [tommytran732/pamac-flatpak#2]
The terminal output

`
amac-flatpack
 -> Could not find all required packages:
	pamac-flatpack (Target)
❯ yay -S pamac-flatpak
:: Checking for conflicts...
:: Checking for inner conflicts...
[Aur:2]  libpamac-flatpak-11.1.0-1  pamac-flatpak-10.2.0-1

  2 libpamac-flatpak                 (Build Files Exist)
  1 pamac-flatpak                    (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==>
:: PKGBUILD up to date, Skipping (2/0): libpamac-flatpak, pamac-flatpak
  2 libpamac-flatpak                 (Build Files Exist)
  1 pamac-flatpak                    (Build Files Exist)
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==>
:: (1/2) Parsing SRCINFO: libpamac-flatpak
:: (2/2) Parsing SRCINFO: pamac-flatpak
==> Creazione del pacchetto: pamac-flatpak 10.2.0-1 (gio 30 dic 2021, 15:37:29)
==> Download dei sorgenti in corso...
  -> È stato trovato pamac-10.2.0.tar.gz
==> Validazione di source file con sha256sums...
    pamac-10.2.0.tar.gz ... Verificato
==> Creazione del pacchetto: libpamac-flatpak 11.1.0-1 (gio 30 dic 2021, 15:37:29)
==> Download dei sorgenti in corso...
  -> È stato trovato libpamac-11.1.0.tar.bz2
==> Validazione di source file con sha256sums...
    libpamac-11.1.0.tar.bz2 ... Verificato
==> Creazione del pacchetto: libpamac-flatpak 11.1.0-1 (gio 30 dic 2021, 15:37:33)
==> Controllo delle dipendenze durante l'avvio in corso...
==> Controllo delle dipendenze durante la compilazione in corso...
==> Download dei sorgenti in corso...
  -> È stato trovato libpamac-11.1.0.tar.bz2
==> Validazione di source file con sha256sums...
    libpamac-11.1.0.tar.bz2 ... Verificato
==> Rimozione dell'esistente directory $srcdir/ in corso...
==> Estrazione dei sorgenti in corso...
  -> Estrazione di libpamac-11.1.0.tar.bz2 usando bsdtar in corso...
==> I sorgenti sono pronti.
==> Creazione del pacchetto: libpamac-flatpak 11.1.0-1 (gio 30 dic 2021, 15:37:42)
==> Controllo delle dipendenze durante l'avvio in corso...
==> Controllo delle dipendenze durante la compilazione in corso...
==> ATTENZIONE: Sto usando il tree esistente di $srcdir/
==> I sorgenti sono pronti.
 -> libpamac-flatpak-11.1.0-1 already made -- skipping build
 -> libpamac-flatpak not satisfied, flushing install queue
[sudo] password di omar:
caricamento dei pacchetti in corso...
risoluzione delle dipendenze in corso...
ricerca dei pacchetti in conflitto in corso...

Pacchetto (1)     Nuova versione  Variazione netta

libpamac-flatpak  11.1.0-1                3,28 MiB

Dimensione totale dei pacchetti da installare:  3,28 MiB

:: Vuoi procedere con l'installazione? [S/n]
(1/1) verifica delle chiavi presenti nel portachiavi         [--------------------------------] 100%
(1/1) verifica dell'integrità dei pacchetti                  [--------------------------------] 100%
(1/1) caricamento dei file dei pacchetti                     [--------------------------------] 100%
(1/1) controllo dei conflitti in corso                       [--------------------------------] 100%
:: Elaborazione delle modifiche al pacchetto...
(1/1) installazione in corso di libpamac-flatpak             [--------------------------------] 100%
:: Esecuzione degli hook di post-transazione...
(1/4) Reloading system manager configuration...
(2/4) Arming ConditionNeedsUpdate...
(3/4) Updating the MIME type database...
(4/4) Reloading system bus configuration...
==> Creazione del pacchetto: pamac-flatpak 10.2.0-1 (gio 30 dic 2021, 15:37:51)
==> Controllo delle dipendenze durante l'avvio in corso...
==> Controllo delle dipendenze durante la compilazione in corso...
==> Download dei sorgenti in corso...
  -> È stato trovato pamac-10.2.0.tar.gz
==> Validazione di source file con sha256sums...
    pamac-10.2.0.tar.gz ... Verificato
==> Rimozione dell'esistente directory $srcdir/ in corso...
==> Estrazione dei sorgenti in corso...
  -> Estrazione di pamac-10.2.0.tar.gz usando bsdtar in corso...
==> Avvio di prepare() in corso...
==> I sorgenti sono pronti.
==> Creazione del pacchetto: pamac-flatpak 10.2.0-1 (gio 30 dic 2021, 15:37:58)
==> Controllo delle dipendenze durante l'avvio in corso...
==> Controllo delle dipendenze durante la compilazione in corso...
==> ATTENZIONE: Sto usando il tree esistente di $srcdir/
==> Rimozione dell'esistente directory $pkgdir/ in corso...
==> Avvio di build() in corso...
The Meson build system
Version: 0.60.3
Source dir: /home/omar/.cache/yay/pamac-flatpak/src/pamac-v10.2.0
Build dir: /home/omar/.cache/yay/pamac-flatpak/src/pamac-v10.2.0/builddir
Build type: native build

../meson.build:1:0: ERROR: Unknown options: "enable-appindicator, enable-flatpak"

A full log can be found at /home/omar/.cache/yay/pamac-flatpak/src/pamac-v10.2.0/builddir/meson-logs/meson-log.txt
==> ERRORE: Si è verificato un errore in build().
    L'operazione sta per essere interrotta...
 -> error making: pamac-flatpak
`

**Comment by tommytran732** [comment]
Should be fixed.
